[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''return self.base.nominal + self.ability.bonus + (self.ability.perma_bonus or 0)'''
position = "before"
payload = '''
if G.GAME.selected_back and G.GAME.selected_back.effect.center.key == "b_bof_l_lightning" then
    return self.ability.bonus + (self.ability.perma_bonus or 0)
end
'''

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
match_indent = true
position = 'after'
pattern = '''
if (key == 'mult' or key == 'h_mult' or key == 'mult_mod') and amount then
'''
payload = '''
    G.GAME.mult_scored_this_run = true
'''
